// <auto-generated />
using EfGate.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ManualDbContext), typeof(ManualDbContextModel))]
