// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EfGate.CompiledModels
{
    public partial class ManualDbContextModel
    {
        private ManualDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("26eea7f5-36b4-4416-966e-d1d7ea1db4a3"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var note = NoteEntityType.Create(this);

            NoteEntityType.CreateAnnotations(note);

            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
