// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: dni_frame.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Wave B — framed protobuf transport (the 4th interop transport).
///
/// Length-prefixed Google.Protobuf frames over a loopback socket: structured binary RPC with no
/// ASP.NET/gRPC runtime (the gRPC-era proto/dni.proto stays untouched as the documented exclusion).
/// Wire framing: [u32 little-endian length][Envelope bytes]. When the PQ secure channel is active the
/// Envelope bytes are AES-256-GCM ciphertext||tag instead (see the pb transport docs); the framing is
/// unchanged. Messages only — codegen with GrpcServices="None" (proven AOT-clean in
/// docs/gpb-nativeaot-findings.md, the Google.Protobuf + Grpc.Tools recipe reused here verbatim).

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Dni_Frame_V1_FeatureDescriptorPb: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var title: String = String()

  var version: String = String()

  var code: String = String()

  var expected: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// result stays an opaque string exactly as it crosses every other transport — for bench/gclab commands
/// it is itself a JSON BenchmarkPayload; for plain features it is the feature's textual output.
nonisolated struct Dni_Frame_V1_FeatureRunPb: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var result: String = String()

  var elapsedMs: Double = 0

  var ok: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_FeaturesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_RunRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_RagRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var query: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_PingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_BenchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var command: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_FeaturesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var features: [Dni_Frame_V1_FeatureDescriptorPb] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_RunResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var run: Dni_Frame_V1_FeatureRunPb {
    get {_run ?? Dni_Frame_V1_FeatureRunPb()}
    set {_run = newValue}
  }
  /// Returns true if `run` has been explicitly set.
  var hasRun: Bool {self._run != nil}
  /// Clears the value of `run`. Subsequent reads from it will return its default value.
  mutating func clearRun() {self._run = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _run: Dni_Frame_V1_FeatureRunPb? = nil
}

nonisolated struct Dni_Frame_V1_PingResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reply: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_RagChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var index: Int32 = 0

  var text: String = String()

  var final: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Typed error — the transport surfaces failures as a payload, never a silent socket close.
nonisolated struct Dni_Frame_V1_ErrorFrame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: Int32 = 0

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Server -> client: the per-boot ML-KEM public key, signed by the per-boot ML-DSA key (whose public
/// half is included so the client can verify the signature). session_id is fresh per handshake; the
/// signature covers (kem_public_key || session_id) and session_id is folded into the HKDF, so replaying a
/// client ciphertext can never resurrect the same session keys. Algorithm names feed the Trust inspector.
nonisolated struct Dni_Frame_V1_HandshakeOffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kemPublicKey: Data = Data()

  var sigPublicKey: Data = Data()

  /// ML-DSA signature over (kem_public_key || session_id)
  var signature: Data = Data()

  /// e.g. "ML-KEM-768"
  var kemAlgorithm: String = String()

  /// e.g. "ML-DSA-65"
  var sigAlgorithm: String = String()

  /// e.g. "AES-256-GCM"
  var cipher: String = String()

  /// fresh 32-byte server randomness per handshake (replay freshness)
  var sessionID: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Client -> server: the ML-KEM ciphertext encapsulating the shared secret.
nonisolated struct Dni_Frame_V1_HandshakeReply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ciphertext: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Dni_Frame_V1_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// client-minted correlation id, echoed in responses (waterfall grouping)
  var requestID: String = String()

  var body: Dni_Frame_V1_Envelope.OneOf_Body? = nil

  var features: Dni_Frame_V1_FeaturesRequest {
    get {
      if case .features(let v)? = body {return v}
      return Dni_Frame_V1_FeaturesRequest()
    }
    set {body = .features(newValue)}
  }

  var run: Dni_Frame_V1_RunRequest {
    get {
      if case .run(let v)? = body {return v}
      return Dni_Frame_V1_RunRequest()
    }
    set {body = .run(newValue)}
  }

  var rag: Dni_Frame_V1_RagRequest {
    get {
      if case .rag(let v)? = body {return v}
      return Dni_Frame_V1_RagRequest()
    }
    set {body = .rag(newValue)}
  }

  var ping: Dni_Frame_V1_PingRequest {
    get {
      if case .ping(let v)? = body {return v}
      return Dni_Frame_V1_PingRequest()
    }
    set {body = .ping(newValue)}
  }

  var bench: Dni_Frame_V1_BenchRequest {
    get {
      if case .bench(let v)? = body {return v}
      return Dni_Frame_V1_BenchRequest()
    }
    set {body = .bench(newValue)}
  }

  var featuresResponse: Dni_Frame_V1_FeaturesResponse {
    get {
      if case .featuresResponse(let v)? = body {return v}
      return Dni_Frame_V1_FeaturesResponse()
    }
    set {body = .featuresResponse(newValue)}
  }

  var runResponse: Dni_Frame_V1_RunResponse {
    get {
      if case .runResponse(let v)? = body {return v}
      return Dni_Frame_V1_RunResponse()
    }
    set {body = .runResponse(newValue)}
  }

  var ragChunk: Dni_Frame_V1_RagChunk {
    get {
      if case .ragChunk(let v)? = body {return v}
      return Dni_Frame_V1_RagChunk()
    }
    set {body = .ragChunk(newValue)}
  }

  var pingResponse: Dni_Frame_V1_PingResponse {
    get {
      if case .pingResponse(let v)? = body {return v}
      return Dni_Frame_V1_PingResponse()
    }
    set {body = .pingResponse(newValue)}
  }

  var error: Dni_Frame_V1_ErrorFrame {
    get {
      if case .error(let v)? = body {return v}
      return Dni_Frame_V1_ErrorFrame()
    }
    set {body = .error(newValue)}
  }

  var handshakeOffer: Dni_Frame_V1_HandshakeOffer {
    get {
      if case .handshakeOffer(let v)? = body {return v}
      return Dni_Frame_V1_HandshakeOffer()
    }
    set {body = .handshakeOffer(newValue)}
  }

  var handshakeReply: Dni_Frame_V1_HandshakeReply {
    get {
      if case .handshakeReply(let v)? = body {return v}
      return Dni_Frame_V1_HandshakeReply()
    }
    set {body = .handshakeReply(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Body: Equatable, Sendable {
    case features(Dni_Frame_V1_FeaturesRequest)
    case run(Dni_Frame_V1_RunRequest)
    case rag(Dni_Frame_V1_RagRequest)
    case ping(Dni_Frame_V1_PingRequest)
    case bench(Dni_Frame_V1_BenchRequest)
    case featuresResponse(Dni_Frame_V1_FeaturesResponse)
    case runResponse(Dni_Frame_V1_RunResponse)
    case ragChunk(Dni_Frame_V1_RagChunk)
    case pingResponse(Dni_Frame_V1_PingResponse)
    case error(Dni_Frame_V1_ErrorFrame)
    case handshakeOffer(Dni_Frame_V1_HandshakeOffer)
    case handshakeReply(Dni_Frame_V1_HandshakeReply)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "dni.frame.v1"

nonisolated extension Dni_Frame_V1_FeatureDescriptorPb: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureDescriptorPb"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}title\0\u{1}version\0\u{1}code\0\u{1}expected\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.expected) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 3)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 4)
    }
    if !self.expected.isEmpty {
      try visitor.visitSingularStringField(value: self.expected, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_FeatureDescriptorPb, rhs: Dni_Frame_V1_FeatureDescriptorPb) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.version != rhs.version {return false}
    if lhs.code != rhs.code {return false}
    if lhs.expected != rhs.expected {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_FeatureRunPb: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeatureRunPb"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}result\0\u{3}elapsed_ms\0\u{1}ok\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.result) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.elapsedMs) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.result.isEmpty {
      try visitor.visitSingularStringField(value: self.result, fieldNumber: 2)
    }
    if self.elapsedMs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.elapsedMs, fieldNumber: 3)
    }
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_FeatureRunPb, rhs: Dni_Frame_V1_FeatureRunPb) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.result != rhs.result {return false}
    if lhs.elapsedMs != rhs.elapsedMs {return false}
    if lhs.ok != rhs.ok {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_FeaturesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeaturesRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_FeaturesRequest, rhs: Dni_Frame_V1_FeaturesRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_RunRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RunRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_RunRequest, rhs: Dni_Frame_V1_RunRequest) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_RagRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RagRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}query\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.query) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.query.isEmpty {
      try visitor.visitSingularStringField(value: self.query, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_RagRequest, rhs: Dni_Frame_V1_RagRequest) -> Bool {
    if lhs.query != rhs.query {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_PingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PingRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_PingRequest, rhs: Dni_Frame_V1_PingRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_BenchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BenchRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}command\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.command) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.command.isEmpty {
      try visitor.visitSingularStringField(value: self.command, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_BenchRequest, rhs: Dni_Frame_V1_BenchRequest) -> Bool {
    if lhs.command != rhs.command {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_FeaturesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FeaturesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}features\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.features) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.features.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.features, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_FeaturesResponse, rhs: Dni_Frame_V1_FeaturesResponse) -> Bool {
    if lhs.features != rhs.features {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_RunResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RunResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}run\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._run) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._run {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_RunResponse, rhs: Dni_Frame_V1_RunResponse) -> Bool {
    if lhs._run != rhs._run {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_PingResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PingResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reply\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reply) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reply.isEmpty {
      try visitor.visitSingularStringField(value: self.reply, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_PingResponse, rhs: Dni_Frame_V1_PingResponse) -> Bool {
    if lhs.reply != rhs.reply {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_RagChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RagChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0\u{1}text\0\u{1}final\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.final) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    if self.final != false {
      try visitor.visitSingularBoolField(value: self.final, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_RagChunk, rhs: Dni_Frame_V1_RagChunk) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.text != rhs.text {return false}
    if lhs.final != rhs.final {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_ErrorFrame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ErrorFrame"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != 0 {
      try visitor.visitSingularInt32Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_ErrorFrame, rhs: Dni_Frame_V1_ErrorFrame) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_HandshakeOffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HandshakeOffer"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}kem_public_key\0\u{3}sig_public_key\0\u{1}signature\0\u{3}kem_algorithm\0\u{3}sig_algorithm\0\u{1}cipher\0\u{3}session_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.kemPublicKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.sigPublicKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.kemAlgorithm) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.sigAlgorithm) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.cipher) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.sessionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.kemPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.kemPublicKey, fieldNumber: 1)
    }
    if !self.sigPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.sigPublicKey, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 3)
    }
    if !self.kemAlgorithm.isEmpty {
      try visitor.visitSingularStringField(value: self.kemAlgorithm, fieldNumber: 4)
    }
    if !self.sigAlgorithm.isEmpty {
      try visitor.visitSingularStringField(value: self.sigAlgorithm, fieldNumber: 5)
    }
    if !self.cipher.isEmpty {
      try visitor.visitSingularStringField(value: self.cipher, fieldNumber: 6)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularBytesField(value: self.sessionID, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_HandshakeOffer, rhs: Dni_Frame_V1_HandshakeOffer) -> Bool {
    if lhs.kemPublicKey != rhs.kemPublicKey {return false}
    if lhs.sigPublicKey != rhs.sigPublicKey {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.kemAlgorithm != rhs.kemAlgorithm {return false}
    if lhs.sigAlgorithm != rhs.sigAlgorithm {return false}
    if lhs.cipher != rhs.cipher {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_HandshakeReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HandshakeReply"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ciphertext\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_HandshakeReply, rhs: Dni_Frame_V1_HandshakeReply) -> Bool {
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Dni_Frame_V1_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Envelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}features\0\u{1}run\0\u{1}rag\0\u{1}ping\0\u{1}bench\0\u{3}features_response\0\u{3}run_response\0\u{3}rag_chunk\0\u{3}ping_response\0\u{1}error\0\u{3}handshake_offer\0\u{3}handshake_reply\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try {
        var v: Dni_Frame_V1_FeaturesRequest?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .features(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .features(v)
        }
      }()
      case 3: try {
        var v: Dni_Frame_V1_RunRequest?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .run(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .run(v)
        }
      }()
      case 4: try {
        var v: Dni_Frame_V1_RagRequest?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .rag(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .rag(v)
        }
      }()
      case 5: try {
        var v: Dni_Frame_V1_PingRequest?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .ping(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .ping(v)
        }
      }()
      case 6: try {
        var v: Dni_Frame_V1_BenchRequest?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .bench(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .bench(v)
        }
      }()
      case 7: try {
        var v: Dni_Frame_V1_FeaturesResponse?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .featuresResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .featuresResponse(v)
        }
      }()
      case 8: try {
        var v: Dni_Frame_V1_RunResponse?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .runResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .runResponse(v)
        }
      }()
      case 9: try {
        var v: Dni_Frame_V1_RagChunk?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .ragChunk(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .ragChunk(v)
        }
      }()
      case 10: try {
        var v: Dni_Frame_V1_PingResponse?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .pingResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .pingResponse(v)
        }
      }()
      case 11: try {
        var v: Dni_Frame_V1_ErrorFrame?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .error(v)
        }
      }()
      case 12: try {
        var v: Dni_Frame_V1_HandshakeOffer?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .handshakeOffer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .handshakeOffer(v)
        }
      }()
      case 13: try {
        var v: Dni_Frame_V1_HandshakeReply?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .handshakeReply(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .handshakeReply(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    switch self.body {
    case .features?: try {
      guard case .features(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .run?: try {
      guard case .run(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .rag?: try {
      guard case .rag(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .ping?: try {
      guard case .ping(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .bench?: try {
      guard case .bench(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .featuresResponse?: try {
      guard case .featuresResponse(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .runResponse?: try {
      guard case .runResponse(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .ragChunk?: try {
      guard case .ragChunk(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .pingResponse?: try {
      guard case .pingResponse(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .error?: try {
      guard case .error(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .handshakeOffer?: try {
      guard case .handshakeOffer(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .handshakeReply?: try {
      guard case .handshakeReply(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Dni_Frame_V1_Envelope, rhs: Dni_Frame_V1_Envelope) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.body != rhs.body {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
